language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1'

install:
  - composer install

notifications:
  email:
    recipients: yankeedudlizz@gmail.com
    on_success: change
    on_failure: always